version: '3.5'

services:  
  mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  db_data: